### ISSUE TITLE
怎么运行啊老哥

### ISSUE THREAD

**Issue by 211guns** [Magicskys/Kiddy#3]
依赖已经安装

**Comment by Magicskys** [comment]
在项目目录下执行go run main.go

**Comment by 211guns** [comment]
没有这个库
Traceback (most recent call last):
  File "./container/monitor.py", line 3, in <module>
    from mitmproxy.tools.dump import DumpMaster
ImportError: No module named tools.dump

**Comment by Magicskys** [comment]
需要在当前环境下执行pip install -r requirements.txt

**Comment by 211guns** [comment]
老哥，已经pip需要的包，但是还是提示确实这个ImportError: No module named tools.dump   导致开代理8000  kiddy抓不到包

**Comment by Magicskys** [comment]
你是python2 还是python3，需要python3环境 ,需要在main.go所在的环境下的python安装该包
也可以手动运行被动式组件python container/monitor.py
